pipeline {
agent any
environment {
       ANYPOINT= credentials(‘ANYPOINT’)
}
Stages {
      Stage(‘Build’) {
              Steps {
                      WithMaven(maven:’maven’){
                                 Sh ‘mvn’ -f mule -jenkins -hello_world/pom.xml clean install’
                        }
                   }
      } 
Stage(‘Deploy’) {
              Steps {
                      WithMaven(maven:’maven’){
                                 Sh ‘mvn’ -f mule -jenkins -hello_world/pom.xml package deploy -Dusername=$ANYPOINT_USR - Dusername=$ANYPOINT_PSW -Denvironment=Sandbox -DmuleDeploy

                        }
                   }
      }
   }
}
